models/raw/estoque_central_tpc/_estoque_central_tpc_schema.yml, profiles.yml
=> Testes dbt

dbt_project.yml
tags criadas e atualizadas para o novo modelo de classificação de riscos
vars:
TAG_CPF: 'projects/rj-sms/locations/us/taxonomies/7948647440833323337/policyTags/7275937608331929015'
TAG_CNS: 'projects/rj-sms/locations/us/taxonomies/7948647440833323337/policyTags/8199751371890630153'
TAG_NOME: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/2632983500029416584'
TAG_TELEFONE: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/6197099915332240403'
TAG_EMAIL: 'projects/rj-sms/locations/us/taxonomies/4827881364676585191/policyTags/6775173897032728488'
TAG_ENDERECO: 'projects/rj-sms/locations/us/taxonomies/6217643325435375844/policyTags/5348387254077392279'
TAG_CRM: 'projects/rj-sms/locations/us/taxonomies/7948647440833323337/policyTags/212997548114276 …
=> Atualização da variavel das tags

tests/generic/assert_chegando_todas_unidades_de_saude.sql
inclusão de condição para não roda em dias de domingo nas unidades da Vitacare.
=> vitacare__estoque_movimento__chegando_todas_unidades

models/raw/prontuario_vitai/_prontuario_vitai__schema.yml
- name: id_material
description: Código de identificação do material cadastrado no prontuário
policy_tags:
- '{{ var ("TAG_MATERIAL") }}'
tests:
- not_null:
name: raw_prontuario_vitai__estoque_movimento__id_material__not_null
config:
where: "estoque_movimento_data > '2023-01-01 '"
=> Inserindo data para inicio da coleta dos movimentos a partir de jan 2023

models/raw/prontuario_vitai/_prontuario_vitai__schema.yml
removido o espaço após a data 2023-01-01
=> Data de listagem alterada

models/raw/prontuario_vitacare/_prontuario_vitacare_schema.yml
acerto de warning para 6 unidades vitacare que ainda não estão fazendo o uso do modulo de farmacia
=> warning vitacae

tests/generic/assert_chegando_todas_unidades_de_saude.sql
Alterado o dia da semana de sunday para Monday, respeitando o case sensitive e seguindo a logica que não ha movimento de dados no domingo, portanto na segunda feira não havará registros
=> Dia da semana alterado

models/raw/prontuario_vitacare/_prontuario_vitacare_schema.yml
id material not null de 100000 para 120000
=> id material not null de 100000 para 120000

models/marts/estoque/_mart_estoque_schema.yml, models/raw/cnes_ftp/_cnes_ftp_schema.yml
inclusão de tags nas tabelas  rj-sms.brutos_cnes_ftp  e rj-sms.projeto_estoque
=> inclusão das tags

.gitignore, models/marts/estoque/_mart_estoque_schema.yml, models/marts/estoque/mart_estoque__movimento.sql
…toque_schema.yml
Este PR adiciona novamente o models de movimento para restaurar o projeto reprocessamento
=> Correção: model movimento para reprocessamento

tests/marts/core/facts/core__estoque__movimento_vs_posicao.sql
=> ajuste no warn

models/marts/core/facts/fct_estoque_movimento.sql, models/marts/core/facts/fct_estoque_posicao.sql
Este PR tem objetivo de corrigir o nome das tabelas mestras de estoque que estavam fora do padrão de taxonomia 
=> Refactor table aliases in fct_estoque_movimento.sql and fct_estoque_posicao.sql

models/raw/sih/_sih_sources.yml, models/raw/sih/raw_sih__indicadores_hospitalares.sql
Este PR corrige o bug no model indicadores hospitalares onde o source não é encontrado.
=> [fix[ indicadores_hospitalares model

models/raw/datasus/_datasus_schema.yml, models/raw/datasus/_datasus_sources.yml, models/raw/datasus/raw_datasus__cbo.sql, models/raw/datasus/raw_datasus__cbo_fam.sql
This commit adds the raw Datasus tables for CBO (cargo) and CBO fam (família). These tables contain information about job positions and job families in the CBO classification system. The tables include columns for identifiers, descriptions, data load dates, and snapshot dates.
New files:
- models/raw/datasus/_datasus_schema.yml
- models/raw/datasus/_datasus_sources.yml
- models/raw/datasus/raw_datasus__cbo.sql
- models/raw/datasus/raw_datasus__cbo_fam.sql
=> feat: Add raw Datasus tables for CBO and CBO fam

models/marts/estoque/_mart_estoque_schema.yml, models/marts/estoque/mart_estoque__posicao_atual.sql, models/marts/estoque/mart_estoque__posicao_atual_agregado.sql
O objetivo deste PR é adiciona no projeto de estoque campo para realizar busca de materiais insensível a caixa alta.
=> feat: Add case-insensitive search for material_id and description

models/intermediate/estoque/int_estoque__dispensacao_media_mensal.sql, models/marts/estoque/mart_estoque__posicao_atual.sql
PR para substituir o CMD utilizado no modelos de estoque, considerando as observações marcadas como outliers. 
=> refactor: Update CMD calculation to use outliers

models/marts/core/facts/sisreg/_facts_sisreg_schema.yml, models/marts/core/facts/sisreg/fct_sisreg_oferta_programada.sql, models/marts/core/facts/sisreg/fct_sisreg_oferta_programada_serie_historica.sql, models/raw/sisreg/_sisreg_schema.yml, models/raw/sisreg/raw_sisreg__oferta_programada.sql
This commit renames the following files:
- `fct_sisreg_escala.sql` to `fct_sisreg_oferta_programada_serie_historica.sql`
- `raw_sisreg__escala.sql` to `raw_sisreg__oferta_programada.sql`
The purpose of this change is to align the file names with the concept of "oferta programada" in the Sisreg system. This improves clarity and consistency in the codebase.
This commit also adds a new model called `fct_sisreg_oferta_programada` wi
=> refactor: Rename files related to oferta programada in sisreg

models/marts/gerenciamento/reprocessamento/gerenciamento_reprocessamento__brutos_prontuario_vitacare__estoque_movimento.sql
The schema name in the gerenciamento_reprocessamento__brutos_prontuario_vitacare__estoque_movimento.sql file is updated from "controle_reprocessamento" to "gerenciamento__reprocessamento". This change improves consistency in the codebase.
=> refactor: Update schema name in gerenciamento_reprocessamento__brutos_prontuario_vitacare__estoque_movimento.sql

README.md, recce.ps1
=> docs: updating readme to include commands to windows and macos

models/intermediate/core/int_profissional_saude__vinculo_estabelecimento_serie_historica.sql, models/marts/core/dimensions/dim_profissional_saude.sql
=> Ajustes na tabela profisional

models/marts/core/facts/estoque/fct_estoque_posicao.sql
Este PR corrige a situação onde não são exibidos itens com estoque zerado quando a posição atual está defasada.
=> feat: Add incremental loading to fct_estoque_posicao.sql

models/intermediate/historico_clinico/alergia/_alergia_schema.yml, models/intermediate/historico_clinico/alergia/int_historico_clinico__alergia__vitai.sql, models/marts/historico_clinico/_historico_clinico_schema.yml, models/marts/historico_clinico/mart_historico_clinico__alergia.sql
=> [Alergias] Modelo inicial de alergias vitai 

models/intermediate/gerenciamento/historico_clinico/int_gerenciamento__historico_clinico__episodio_contagem.sql
=> Conserta query de gerenciamento de perda de dados

macros/clean_cid.sql, models/intermediate/cid/int_historico_clinico__cid_categoria.sql, models/intermediate/cid/int_historico_clinico__cid_subcategoria.sql, models/intermediate/historico_clinico/episodio/_historico_clinico_schema.yml, models/intermediate/historico_clinico/episodio/int_historico_clinico__episodio__vitacare.sql, models/intermediate/historico_clinico/episodio/int_historico_clinico__episodio__vitai.sql, models/marts/historico_clinico/_mart_historico_clinico_schema.yml, models/marts/historico_clinico/mart_historico_clinico__episodio.sql, models/marts/historico_clinico_app/mart_historico_clinico_app__episodio.sql, models/raw/datasus/_datasus_schema.yml, models/raw/datasus/raw_datasus__cid10.sql
=> Adiciona resumo dos CIDs do episódio

models/intermediate/historico_clinico/episodio/_historico_clinico_schema.yml, models/intermediate/historico_clinico/episodio/int_historico_clinico__episodio__vitacare.sql, models/marts/historico_clinico/_mart_historico_clinico_schema.yml, models/marts/historico_clinico/mart_historico_clinico__episodio.sql, models/marts/historico_clinico_app/mart_historico_clinico_app__episodio.sql
=> Retira filtro de CIDs e adiciona procedimentos

models/intermediate/historico_clinico/episodio/int_historico_clinico__episodio__vitacare.sql
=> [HCI] Adiciona profissional Vitacare

models/marts/core/dimensions/_dimensions_schema.yml, models/marts/core/dimensions/dim_profissional_saude.sql, models/marts/core/dimensions/dim_vinculo_profissional_saude_estabelecimento.sql
=> Reapontamento de tabela mestre de profissionais e agrupamento de CBO

models/intermediate/historico_clinico/episodio/int_historico_clinico__episodio__vitacare.sql
=> [HCI] Profissional vitacare vindo apenas de prontuário

models/marts/core/dimensions/rio/dim_profissional_sus_rio_historico.sql, models/raw/sheets/_sheets_schema.yml, models/raw/sheets/_sheets_sources.yml, models/raw/sheets/raw_sheets__saude_profissionais_cns_cpf_aux.sql
OBS: É preciso colocar a tabela auxiliar no fluxo do sheets, a primeira inserção foi manual direto no BQ.
=> [CNES] Adiciona etapa de enriquecimento de cpfs à base histórica de profissionais 

models/raw/sheets/_sheets_schema.yml, models/raw/sheets/_sheets_sources.yml, models/raw/sheets/raw_sheets__assistencial_procedimento.sql, models/raw/sheets/raw_sheets__saude_profissionais_cns_cpf_aux.sql
=> Cnes subgeral

models/marts/core/dimensions/dim_profissional_saude.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__dtw__atendimento.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__dtw__boletim.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__dtw__internacao.sql
=> Conserta erros da materialização

models/marts/subgeral/censo_hospitalar/_mart_prontuario_vitai__schema.yml, models/marts/subgeral/censo_hospitalar/mart_prontuario_vitai__cid.sql
=> Tabela de CIDs para Censo hospitalar

models/marts/dit/historico_clinico_app/_mart_historico_clinico_app_schema.yml, models/marts/subgeral/monitora_reg/_mart_monitora_reg_schema.yml
=> [MONITORA REG] Naming data tests

.gitignore, models/intermediate/dit/historico_clinico/episodio/int_historico_clinico__episodio__vitacare.sql, models/intermediate/dit/historico_clinico/episodio/int_historico_clinico__episodio__vitai.sql, models/marts/dit/historico_clinico/mart_historico_clinico__episodio.sql, models/marts/subgeral/censo_hospitalar/_mart_censo_hospitalar__schema.yml, models/marts/subgeral/censo_hospitalar/mart_censo_hospitalar__vitai_cid.sql, models/marts/subgeral/censo_hospitalar/mart_prontuario_vitai__cid.sql
=> Resolve problema de Linhagem

models/marts/core/facts/sisreg/_facts_sisreg_schema.yml, models/marts/core/facts/sisreg/fct_sisreg_oferta_programada_serie_historica.sql
Adiciona descritores nominais para os campos de procedimentos e estabelecimentos.
=> [SISREG] Oferta Programada

models/marts/dit/historico_clinico_app/_mart_historico_clinico_app_schema.yml
Adiciona metadados de colunas para as tabelas `sumario`, `paciente` e `episodio_assistencial` do dataset `rj-sms.app_historico_clinico`
=> chore: add column descriptions for hci tables

models/intermediate/dit/historico_clinico/paciente/int_historico_clinico__paciente__vitacare.sql
=> [HCI] Conserta casos de sexo em inglês

models/intermediate/dit/historico_clinico/episodio/int_historico_clinico__episodio__vitai.sql
=> [HCI] Adiciona coalesce em estabelecimento vitai

models/intermediate/dit/historico_clinico/obito/int_historico_clinico__obito__vitai.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__paciente.sql
=> [HCI] Puxa cpf da tabela de pacientes vitai para enriquecer a tabela de óbitos

models/intermediate/dit/historico_clinico/episodio/int_historico_clinico__episodio__vitai.sql, models/marts/dit/historico_clinico/mart_historico_clinico__episodio.sql
=> [HCI] Adiciona datetime em medicamentos administrados Vitai

models/intermediate/dit/historico_clinico/episodio/_historico_clinico_schema.yml, models/marts/dit/historico_clinico/_mart_historico_clinico_schema.yml, models/marts/dit/historico_clinico_app/_mart_historico_clinico_app_schema.yml, models/marts/dit/historico_clinico_app/mart_historico_clinico_app__episodio.sql
=> [HCI] Adiciona coluna datetime a camada app

models/marts/core/dimensions/rio/_dimensions_rio_schema.yml, models/marts/core/dimensions/rio/dim_profissional_sus_rio_historico.sql, models/marts/subgeral/cnes/_mart_cnes_subgeral_schema.yml, models/marts/subgeral/cnes/mart_cnes_subgeral__profissionais_mrj_sus.sql
Adding id_sus column for professionals, date of begining and ending of the contract, and also changing the structure of the address data on the subgeral project model.
=> [CNES PROFISSIONAIS] Adding new columns

models/marts/dit/historico_clinico_app/mart_historico_clinico_app__episodio.sql
=> [HCI] Ordenamento de medicamentos administrados

models/intermediate/subgeral/monitora_reg/int_mva__carga_horaria_ambulatorial_mensal.sql, models/intermediate/subgeral/monitora_reg/int_mva__oferta_programada_mensal.sql, models/intermediate/subgeral/monitora_reg/int_mva__oferta_programada_mensal_por_procedimento.sql, models/intermediate/subgeral/monitora_reg/int_mva__oferta_programada_mensal_por_unidade.sql, models/marts/subgeral/monitora_reg/_mart_monitora_reg_schema.yml, models/marts/subgeral/monitora_reg/mart_monitora_reg__monitor_vagas_ambulatoriais.sql
We were losing some values in important steps when rounding (getting lots of zeros).
=> [MONITORA REG] MVA - fix/ Changes round to 3 decimal places

models/marts/core/dimensions/_dimensions_schema.yml, models/marts/core/dimensions/dim_profissional_saude.sql
=> [Datalake] Descarta profissionais duplicados

dbt_project.yml, profiles.yml
@TanookiVerde esse PR tem objetivo de facilitar a gestão de multiplos ambientes de dbt pela minha parte e do @d116626.
Será necessário pedir para que todos os usuários do `queries-rj-sms` façam essa modificação no seu arquivo local de profile:
=> Update dbt profile configuration from 'default' to 'sms'

models/intermediate/dit/historico_clinico/episodio/int_historico_clinico__episodio__vitacare.sql, models/intermediate/dit/historico_clinico/episodio/int_historico_clinico__episodio__vitai.sql
=> [HCI] Reapontando CID de internação para CID de saída e normalizando campo

macros/capitalize_first_letter.sql, models/marts/dit/historico_clinico_app/mart_historico_clinico_app__episodio.sql
=> [HC] Reduzindo campo de descrição de especialidade

.github/workflows/dbt-compile.yaml, dbt_project.yml, models/marts/core/dimensions/rio/dim_estabelecimento_sus_rio_historico.sql, models/raw/area_programatica/_area_programatica_schema.yml, models/raw/area_programatica/_area_programatica_sources.yml, models/raw/area_programatica/raw_area_programatica__bairros_aps.sql, models/raw/cnes_web/raw_cnes_web__estabelecimento.sql, models/raw/geo_pgeo3/_geo_pgeo3_schema.yml, models/raw/geo_pgeo3/_geo_pgeo3_sources.yml, models/raw/geo_pgeo3/raw_geo_pgeo3__estabelecimentos_coordenadas.sql
=> [CNES] Enriching AP information and fixing neighborhood errors

.github/workflows/dbt-compile.yaml, dbt_project.yml, models/raw/minhasaude_mongodb/_minhasaude_mongodb__schema.yml, models/raw/minhasaude_mongodb/raw_minhasaude_mongodb__modulos_perfil_acessos.sql, models/raw/minhasaude_mongodb/raw_minhasaude_mongodb__perfil_acessos.sql
=> [MINHA SAUDE] Mongo DB  - Acessos

models/raw/prontuario_vitacare/raw_prontuario_vitacare__vacina.sql
=> [Vacinas] Conserta id_surrogate

models/marts/dit/historico_clinico/_mart_historico_clinico_schema.yml, models/marts/subpav/indicadores_paciente/mart_subpav__indicadores_recentes.sql, tests/generic/assert_episodios_com_paciente_cadastrado.sql
=> [Erros DBT] Renomeia teste e conserta tabela SUBPAV

models/intermediate/dit/historico_clinico/obito/int_historico_clinico__obito__vitai.sql
=> Adiciona macro de processamento de nulos

models/raw/prontuario_vitai/_prontuario_vitai__schema.yml, models/raw/prontuario_vitai/_prontuario_vitai_sources.yml, models/raw/prontuario_vitai/raw_prontuario_vitai__alergia.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__alta.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__atendimento.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__boletim.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__cirurgia.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__classificacao_risco.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__diagnostico.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__exame.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__internacao.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__paciente.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__profissional.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__relato_cirurgico.sql, models/raw/prontuario_vitai/raw_prontuario_vitai__resumo_alta.sql
=> [HCI] Adiciona modelos contínuos na cama raw da Vitai

models/marts/core/dimensions/dim_equipe.sql, models/marts/core/dimensions/dim_profissional_saude.sql
=> [Datalake] Conserta erros dbt

models/intermediate/dit/historico_clinico/episodio/_historico_clinico_schema.yml
=> [Datalake] Configura limite para teste Vitacare na camada intermediária

models/marts/dit/historico_clinico/_mart_historico_clinico_schema.yml, models/marts/dit/historico_clinico_app/_mart_historico_clinico_app_schema.yml
=> [Datalake] Estende configuração dos testes para camada app e mart

dbt_project.yml, models/marts/subgeral/projeto_nps/_mart_projeto_nps_schema.yml, models/marts/subgeral/projeto_nps/mart_projeto_nps__episodios.sql
Builds the initial model for the NPS project.  
This model focuses on specific care episodes starting in 2025, incorporating enhancements relevant to the projects objectives.
=> [PROJETO NPS] New model

models/marts/dit/historico_clinico/_mart_historico_clinico_schema.yml, models/marts/dit/historico_clinico/mart_historico_clinico__episodio.sql, models/marts/dit/historico_clinico/mart_historico_clinico__paciente.sql
=> [Datalake] Cria chave entre episodios e pacientes

models/raw/prontuario_vitacare/_prontuario_vitacare_schema.yml, models/raw/prontuario_vitacare/raw_prontuario_vitacare__ficha_a.sql
=> [Datalake] Adiciona chave anonimizada de paciente na tabela da Ficha A

models/intermediate/dit/historico_clinico/episodio/int_historico_clinico__episodio__vitacare.sql
=> [HCI] Conserta campo de medidas

dbt_project.yml, macros/process_null.sql, models/marts/subgeral/tempo_medio_espera/_mart_tme_schema.yml, models/marts/subgeral/tempo_medio_espera/mart_tme__procedimento_mensal.sql, models/marts/subgeral/tempo_medio_espera/mart_tme__tempos_espera.sql, models/raw/ser_metabase/base_brutos_ser_metabase_staging_TB_SOLICITACOES.sql, models/raw/sisreg_api/_sisreg_api__schema.yml, models/raw/sisreg_api/_sisreg_api__sources.yml, models/raw/sisreg_api/raw_sisreg_api__marcacoes.sql, models/raw/sisreg_api/raw_sisreg_api__solicitacoes.sql
i. sisreg solicitacoes
ii. sisreg marcacoes (agendamentos / execução)
iii. sisreg tempos de espera
iv. sisreg tempos medios de espera
=> [SISREG API] Implements new models and its schemas

models/raw/aplicacao_hci/_aplicacao_hci_sources.yml, models/raw/ergon/_ergon_sources.yml, models/raw/prontuario_vitai/_prontuario_vitai_sources.yml
=> [Datalake] Cria teste source freshness para o Ergon e Acessos HCI

models/intermediate/dit/historico_clinico/acessos/int_acessos__automatico.sql, models/intermediate/dit/historico_clinico/acessos/int_acessos__manual.sql, models/marts/core/dimensions/dim_profissional_saude.sql, models/marts/dit/historico_clinico_app/mart_historico_clinico_app__acessos.sql, models/raw/cnes_gdb/_cnes_ftp_sources.yml, models/raw/cnes_gdb/raw_cnes_gdb__estabelecimento.sql, models/raw/cnes_gdb/raw_cnes_gdb__profissional.sql, models/raw/cnes_gdb/raw_cnes_gdb__vinculo.sql
=> [HCI] Reaponta acessos para tabelas cgcca e retira Ergon

models/marts/dit/historico_clinico_app/mart_historico_clinico_app__acessos.sql
=> Conserta camada app

models/intermediate/dit/historico_clinico/acessos/int_acessos__automatico.sql, models/intermediate/dit/historico_clinico/acessos/int_acessos__manual.sql, tests/raw/mart_sheets__usuarios_permitidos__validacao.sql
=> [HCI] Adiciona testes para tabela manual de acessos e CAP 51 nos acessos automatizados

models/marts/core/dimensions/rio/dim_estabelecimento_sus_rio_historico.sql, models/raw/geo_pgeo3/raw_geo_pgeo3__estabelecimentos_coordenadas.sql
=> [Datalake] Adapta modelo pgeo3 para lidar com duplicatas

models/marts/dit/historico_clinico_app/mart_historico_clinico_app__episodio.sql
=> [HCI] Resolve nulos em entry_datetime

models/marts/dit/historico_clinico_app/mart_historico_clinico_app__episodio.sql
=> [HCI] Retira pacientes de determinados CIDs

models/raw/prontuario_vitai/raw_prontuario_vitai__paciente.sql
- Tratamento de casos com ".0" na coluna numero_prontuario
=> fix: treating cases with ".0" in numero_prontuarios

models/raw/prontuario_vitacare/raw_prontuario_vitacare__ficha_a.sql
- Adição de "NÃO SABE LER/ESCREVER" no tratamento da coluna escolaridade na tabela `ficha_a` em `brutos_prontuarios_vitacare`
=> fix: fixing bug in the escolaridade column

models/raw/plataforma_smsrio/raw_plataforma_smsrio__estabelecimento_contato.sql
- Aplicação do processamento de registros nulos no modelo da tabela `brutos_plataforma_smsrio_estabelecimento_contato`. que é utilizado na tabela de `saude_dados_mestre.estabelecimento`.
https://app.clickup.com/t/86a8exd76
=> feat: applyin null processing to estabelecimento_contato

models/intermediate/dit/historico_clinico/paciente/int_historico_clinico__paciente__vitacare.sql
=> [HCI] Ordenando equipes de familia

models/raw/plataforma_smsrio/raw_plataforma_smsrio__estabelecimento_contato.sql
=> [Datalake] Adiciona nome em colunas com macro process_null

models/raw/aplicacao_hci/raw_aplicacao_hci__userhistory.sql
=> [HCI] Adiciona id unico de ação para contabilizar buscas sem duplicatas

macros/dedup_array_of_struct.sql, models/intermediate/dit/historico_clinico/acessos/int_acessos__automatico.sql, models/intermediate/dit/historico_clinico/acessos/int_acessos__manual.sql, models/marts/dit/historico_clinico_app/mart_historico_clinico_app__acessos.sql, models/marts/dit/historico_clinico_app_treinamento/mart_historico_clinico_app_treinamento__acessos.sql
=> [HCI] Renomeia coluna em tabela de acessos

macros/remove_double_quotes.sql
=> feat: add macro to remove double quotes from strings

models/raw/sih/_sih_schema.yml, models/raw/sih/raw_sih__autorizacoes_internacoes_hospitalares.sql, models/raw/sih/raw_sih__internacoes_mrj.sql
- Alteração no nome do modelo das tabelas do sih
- Tratamento de colunas nulas
- Processamento de colunas categóricas
=> update: altera o nome do modelo das tabelas do sih

macros/parse_date.sql, macros/subpav/_macros_schema.yml, macros/subpav/extract_competencia_from_path.sql, macros/subpav/normalize_null.sql, models/raw/informes_vitacare/_informes_vitacare_schema.yml, models/raw/informes_vitacare/_informes_vitacare_sources.yml, models/raw/informes_vitacare/raw_informes_vitacare_criancas_menores_5_anos.sql, models/raw/informes_vitacare/raw_informes_vitacare_estado_nutricional_sisvan.sql, models/raw/informes_vitacare/raw_informes_vitacare_ficha_c_v2.sql, models/raw/informes_vitacare/raw_informes_vitacare_indicadores_cg_variavel_1.sql, models/raw/informes_vitacare/raw_informes_vitacare_indicadores_cg_variavel_2.sql, models/raw/informes_vitacare/raw_informes_vitacare_indicadores_cg_variavel_3.sql, models/raw/informes_vitacare/raw_informes_vitacare_listagem_pacientes_tea.sql
Modelos de informes SUBPAV utilizados para calculos de indicadores e qualificação de registro.
=> [Plataforma SUBPAV] Adicionando modelos dos informes

models/raw/prontuario_vitacare/_prontuario_vitacare_schema.yml, models/raw/prontuario_vitacare/raw_prontuario_vitacare__vacina.sql
=> [Datalake] Contorna problema de tipo em modelo de vacinas

models/raw/prontuario_vitacare/base/base_prontuario_vitacare__atendimento_historico.sql, models/raw/prontuario_vitacare/base/base_prontuario_vitacare__paciente_continuo.sql, models/raw/prontuario_vitacare/base/base_prontuario_vitacare__paciente_historico.sql, models/raw/prontuario_vitacare/raw_prontuario_vitacare__paciente.sql
=> [HCI] Adiciona backup Vitacare no HCI

macros/padronize_telefone.sql, models/marts/dit/historico_clinico_app/mart_historico_clinico_app__paciente.sql
- Utilização da macro `padronize_telefone` nas colunas `phone`, `family_clinic.phone` e `family_health_team.phone` 
https://app.clickup.com/t/86a907fpt
=> [HCI App] FIX: Padronização das colunas de telefone

models/raw/prontuario_vitai/_prontuario_vitai_sources.yml
- Alteração do campo `loaded_at_field` de datahora para datalake_loaded_at
- Remoção do parâmetro `filter`
=> [Vitai] -  Atualização dos parâmetros de source freshness

models/intermediate/dit/historico_clinico/paciente/int_historico_clinico__paciente__vitacare.sql, models/raw/prontuario_vitacare/_prontuario_vitacare_schema.yml, models/raw/prontuario_vitacare/base/base_prontuario_vitacare__atendimento_historico.sql, models/raw/prontuario_vitacare_historico/raw_prontuario_vitacare_historico__cadastro.sql, tests/generic/assert_episodios_com_paciente_cadastrado.sql
=> FIX: Registros duplicados

models/raw/prontuario_vitai/_prontuario_vitai_sources.yml, models/raw/prontuario_vitai/raw_prontuario_vitai__basecentral__consistencia_etl.sql
- Adição do modelo para a tabela `basecentral__consistencia_etl`
=> [Vitai] - Adição de modelo da tabela basecentral__consistencia_etl 

models/intermediate/dit/historico_clinico/paciente/int_historico_clinico__paciente__vitacare.sql, models/raw/prontuario_vitacare/base/base_prontuario_vitacare__paciente_continuo.sql, models/raw/prontuario_vitacare/base/base_prontuario_vitacare__paciente_historico.sql, models/raw/prontuario_vitacare/raw_prontuario_vitacare__paciente.sql
=> [HCI] Ajustes no prontuario vitacare

models/intermediate/subgeral/sisreg/int_sisreg__unidades_executantes.sql, models/intermediate/subgeral/sisreg/int_sisreg__unidades_solicitantes.sql, models/marts/subgeral/sisreg/_mart_sisreg_schema.yml, models/marts/subgeral/sisreg/marts_sisreg__unidades.sql
schema asked by the `regulai` devs
=> [SISREG] refact: all sisreg health unities in just one model

dbt_project.yml, models/raw/siscan_web/_siscan_web__schema.yml, models/raw/siscan_web/_siscan_web__sources.yml, models/raw/siscan_web/raw_siscan_web__laudos.sql
Sistema de Informação de Câncer
=> [SISCAN] feat: add new model for mammography exam results

macros/aux_remove_person_description.sql, macros/aux_remove_prefix.sql, macros/aux_remove_suffix.sql, macros/eliminate_babies.sql, macros/is_same_name.sql, macros/process_null.sql, macros/proper_br.sql, macros/remove_duplicate_whitespace.sql, macros/remove_invalid_names.sql, models/intermediate/dit/historico_clinico/paciente/int_historico_clinico__paciente__smsrio.sql, models/intermediate/dit/historico_clinico/paciente/int_historico_clinico__paciente__vitacare.sql, models/intermediate/dit/historico_clinico/paciente/int_historico_clinico__paciente__vitai.sql, models/marts/dit/historico_clinico/mart_historico_clinico__paciente.sql, models/marts/dit/historico_clinico_app/_mart_historico_clinico_app_schema.yml, models/marts/dit/historico_clinico_app/mart_historico_clinico_app__busca.sql
me deixei levar um pouquinho na tarefa herculeana que é tratar nomes ..........
=> [HCI] feat: `nome_social` em `app_historico_clinico.busca`

models/marts/subgeral/sisreg/_mart_sisreg_schema.yml, models/marts/subgeral/sisreg/marts_sisreg__solicitacoes.sql, models/raw/sisreg_api/raw_sisreg_api__agendados.sql, models/raw/sisreg_api/raw_sisreg_api__autorizados.sql, models/raw/sisreg_api/raw_sisreg_api__cancelados.sql, models/raw/sisreg_api/raw_sisreg_api__devolvidos.sql, models/raw/sisreg_api/raw_sisreg_api__executados.sql, models/raw/sisreg_api/raw_sisreg_api__fila.sql, models/raw/sisreg_api/raw_sisreg_api__marcacoes.sql, models/raw/sisreg_api/raw_sisreg_api__negados.sql, models/raw/sisreg_api/raw_sisreg_api__solicitacoes.sql
Consolida solicitacoes e marcacoes da API do SISREG, padroniza tipos e
enriquece com atributos do HCI.
- Incremental (merge) com unique_key = solicitacao_id
- Particionado por data_solicitacao (month); cluster por
id_cnes_unidade_solicitante, id_cnes_unidade_executante, id_procedimento_sisreg
- on_schema_change = sync_all_columns
- Desduplica pela maior data_atualizacao_registro (ROW_NUMBER QUALIFY)
- Enriquecimento: paciente_contato_hci, paciente_cns_hci
- Schema: docs + testes (unique/not_null, relationships para unidades, accepted_values em paciente_sexo)
=> [SISREG] feat: new sisreg marcacoes/solicitacoes consolidated model

models/marts/core/dimensions/_dimensions_schema.yml, models/marts/core/dimensions/dim_estabelecimento.sql, models/raw/sheets/_sheets_sources.yml, models/raw/sheets/raw_sheets__projeto_odontologia_historico.sql, models/raw/sheets/raw_sheets__projeto_odontologia_historico_ap.sql, models/raw/sheets/raw_sheets__projeto_odontologia_sigtap_odo.sql
Adiciona os modelos para as planilhas de odonto e adiciona indicador de atendimento odontologico na tabela de estabelecimentso em saude_dados_mestre.
=> [Google Sheets] - Adiciona modelos das planilhas de odonto e alteração em tabela de estabelecimentos
